# Generated by Django 4.0.dev20210727084151 on 2021-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('check_date', models.DateTimeField(verbose_name='date checked')),
            ],
        ),
    ]
